service: watchtree-api

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stackName: watchtree-api
  apiName: watchtree-api
  timeout: 15

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-offline

custom:
  tscpaths:
    src: src

functions:
  app:
    name: watchtree-api
    handler: src/serverless.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
