service: watchtree-api

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: ${env:AWS_CONFIG_REGION}
  stackName: watchtree-api
  apiName: watchtree-api
  deploymentBucket:
    name: watchtree-api
    serverSideEncryption: AES256
  timeout: 15

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths
  - serverless-dotenv-plugin
  - serverless-deployment-bucket
  - serverless-offline

custom:
  tscpaths:
    src: src

functions:
  app:
    name: watchtree-api
    handler: src/serverless.handler
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
